# Code for feature engineering of item, geo and UI

#### Author: </p>
Xu Chenqi  徐琛奇  1901212653   Quantitate Finance 19

#### Statement：</p>
The code part does not refer to the existing code about the problem. The code is all written by the author herself.</p>

In [2]:
from threading import Thread
import pandas as pd
from collections import Counter
import  numpy as np

# Data-2days

In [11]:
loc = 'D:/Github/PHBS_MLF_2019/Data/Two Days/tianchi_fresh_comp_train_user_'
df1_1= pd.read_excel(loc + 'train1.xlsx')
df1_2= pd.read_excel(loc + 'train2.xlsx')
df1_3= pd.read_excel(loc + 'train3.xlsx')
df1_4= pd.read_excel(loc + 'train4.xlsx')
df1_5= pd.read_excel(loc + 'test.xlsx')
'''
train1_15,16,17
train2_14,15,16
train3_13,14,15
train4_9,10,11
test_16,17,18
'''

'\ntrain1_15,16,17\ntrain2_14,15,16\ntrain3_13,14,15\ntrain4_9,10,11\ntest_16,17,18\n'

In [12]:
for i in range(1,6):
    locals()['df1_'+str(i)]['time1']=locals()['df1_'+str(i)]['time'].map(lambda x:x.split(" ")[0])

df1=df1_1.loc[(df1_1["time1"]!="2014-12-17")]
df2=df1_2.loc[(df1_2["time1"]!="2014-12-16")]
df3=df1_3.loc[(df1_3["time1"]!="2014-12-15")]
df4=df1_4.loc[(df1_4["time1"]!="2014-12-11")]
df5=df1_5.loc[(df1_5["time1"]!="2014-12-18")]

for i in range(1,6):
    print(locals()['df'+str(i)].head())

      user_id    item_id  behavior_type user_geohash  item_category  \
5   100029775   56574541              1          NaN           6689
10  100029775  287413918              1          NaN           5689
13  100029775  365811867              1          NaN           5894
15  100029775  297443044              1          NaN          10223
16  100029775  223294204              1          NaN          12564

             time       time1
5   2014-12-16 12  2014-12-16
10  2014-12-16 15  2014-12-16
13  2014-12-16 13  2014-12-16
15  2014-12-16 15  2014-12-16
16  2014-12-16 15  2014-12-16
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  220586551              1          NaN           7079
2  10001082  209290607              1          NaN           5894
3  10001082   22667958              1      95qogn4          10523
4  10001082  125083630              1          NaN           4722

            time       time1
0  2014-12-15 08  2014-12-15
1  2014-12-14 03  2014-12-14
2  2014-12-14 16  2014-12-14
3  2014-12-15 08  2014-12-15
4  2014-12-14 03  2014-12-14
    user_id    item_id  behavior_type user_geohash  item_category  \
1  10001082  275221686              1          NaN          10576
2  10001082  220586551              1          NaN           7079
3  10001082  209290607              1          NaN           5894
5  10001082  125083630              1          NaN           4722
7  10001082  275221686              1          NaN          10576

            time       time1
1  2014-12-13 14  2014-12-13
2  2014-12-14 03  2014-12-14
3  2014-12-14 16  2014-12-14
5  2014-12-14 03  2014-12-14
7  2014-12-13 14  2014-12-13
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  282931871              1          NaN           6000
1  10001082   62687596              1          NaN           6000
2  10001082   90957005              1          NaN           6000
3  10001082   90957005              1          NaN           6000
4  10001082   17500214              1          NaN           6000

            time       time1
0  2014-12-10 13  2014-12-10
1  2014-12-10 13  2014-12-10
2  2014-12-10 13  2014-12-10
3  2014-12-10 13  2014-12-10
4  2014-12-10 13  2014-12-10
     user_id    item_id  behavior_type user_geohash  item_category  \
0   10001082  275221686              1          NaN          10576
1   10001082     582649              1      95qobbk          12147
2   10001082  275221686              1          NaN          10576
3   10001082  188586750              1      95qobcf          12147
5  100029775   61251128              1      9t4qccd           5894

            time       time1
0  2014-12-17 05  2014-12-17
1  2014-12-17 18  2014-12-17
2  2014-12-17 05  2014-12-17
3  2014-12-17 18  2014-12-17
5  2014-12-17 17  2014-12-17

In [13]:
for i in range(1,6):
    locals()['df'+str(i)]=locals()['df'+str(i)].copy(deep=True)

def feature(df):
    df['behavior_type1']=df['behavior_type'].apply(lambda x: list(str(x)))
    df['user_id1'] = df['user_id'].apply(lambda x: [str(x)])
    df['item_id1'] = df['item_id'].apply(lambda x: [str(x)])
    df['user_item_pair']=df['user_id'].map(str)+'-'+df['item_id'].map(str)
    df['user_geohash1'] = df['user_geohash'].apply(lambda x: 0 if x=='nan' else str(x)[:3])
    #groupby
    a = df.groupby('user_id')['behavior_type1'].sum()
    b = df.groupby('item_id')['behavior_type1'].sum()
    c = df.groupby('item_id')['user_id1'].sum()
    d=df.groupby(['user_id','item_id'])['behavior_type1'].sum()
    e=df.groupby(['user_id','item_id'])['item_id1'].sum()
    f= df.groupby('user_geohash1')['behavior_type1'].sum()
    data = pd.DataFrame()
    data['Behavior_list'] = a
    data1 = pd.DataFrame()
    data1['Behavior_list'] = b
    data2 = pd.DataFrame()
    data2['user_id_list'] = c
    data3=pd.DataFrame()
    data3['Behavior_list']=d
    data4=pd.DataFrame()
    data4['item_id_list']=e 
    data5 = pd.DataFrame()
    data5['behavior_list'] = f
    # count the number of acts of each group
    data1['Number_of_acts'] = data2['user_id_list'].apply(lambda x: len(x))
    data3['Number_of_acts_UI'] = data4['item_id_list'].apply(lambda x: len(x))
    '''
    print('data1:',end='\n')
    print(data1.head(2),end='\n')
    print('data3:',end='\n')
    print(data3.head(2),end='\n')
    '''
############# Feature of item################
####### Statistics
    #Number of times the product was purchased
    data['2_item_buy'] = data['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    #Number of users who purchased the item
    data1['2_item_buypeople'] = data1['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    #Number of times the product was viewed
    data['2_item_view'] = data['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #Number of users who viewed the item
    data1['2_item_viewpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #Number of times the product was collected
    data['2_item_collect'] = data['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #Number of users who collected the item
    data1['2_item_collectpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #Number of times the product was carted
    data['2_item_add'] = data['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    # Number of users who carted the item
    data1['2_item_addpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])

####### Ratio
    #Number of times the product was purchased/Number of times the product was viewed
    data['2_item_buy_view'] = data['2_item_buy']/data['2_item_view']
    #Number of users who purchased the item/Number of users who viewed the item
    data1['2_item_buypeople_viewpeople'] = data1['2_item_buypeople']/data1['2_item_viewpeople']
    #Number of times the product was purchased/Number of times the product was collected
    data['2_item_buy_collect'] = data['2_item_buy'] / data['2_item_collect']
    #Number of users who purchased the item/Number of users who collected the item
    data1['2_item_buypeople_collectpeople'] = data1['2_item_buypeople']/data1['2_item_collectpeople']
    #Number of times the product was purchased/Number of times the product was carted
    data['2_item_buy_add'] = data['2_item_buy'] / data['2_item_add']
    #Number of users who purchased the item/Number of users who carted the item
    data1['2_item_buypeople_addpeople'] = data1['2_item_buypeople']/data1['2_item_addpeople']
    #Number of users who make multiple purchases/Number of users who purchased the product in the two days
    data1['2_item_frequentbuypeople_buypeople'] = data1['2_item_buypeople'] / data1['Number_of_acts']
    #Number of users who viewed the product multiple times/Number of users who purchased the product in the two days
    data1['2_item_frequentviewpeople_viewpeople'] = data1['2_item_viewpeople'] / data1['Number_of_acts']
    #Number of users who collected the product multiple times/Number of users who purchased the product in the two days 
    data1['2_item_frequentcollectpeople_collectpeople'] = data1['2_item_collectpeople'] / data1['Number_of_acts']
    #Number of users who carted the product multiple times/Number of users who purchased the product in the two days
    data1['2_item_frequentaddpeople_addpeople'] = data1['2_item_addpeople'] / data1['Number_of_acts']
    data = data.reset_index()
    data1 = data1.reset_index()
    '''
    print('data:',end='\n')
    print(data.head(2),end='\n')
    print('data1:',end='\n')
    print(data1.head(2),end='\n')
    print('item成功',end='\n')
    '''
############# Feature of GEO(geographic location)################
    data5['4_geo_view'] = data5['behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    data5['4_geo_collect'] = data5['behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    data5['4_geo_add'] = data5['behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    data5['4_geo_buy'] = data5['behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    data5['behavior_total'] = data5['behavior_list'].apply(lambda x: len(x))
    #Number of items purchased in the area / Total number of users in the area
    data5['4_geo_purchasepower'] = data5['4_geo_buy']/data5['behavior_total']
    #Number of items purchased in the area / Number of goods viewed in the area
    data5['4_geo_buy_view'] = data5['4_geo_buy']/data5['4_geo_view']
    #Number of goods purchased in the area / Number of goods collected in the area   
    data5['4_geo_buy_collect'] = data5['4_geo_buy']/data5['4_geo_collect']
    #Number of goods purchased in the area to / Number of goods carted in the area    
    data5['4_geo_buy_add'] = data5['4_geo_buy']/data5['4_geo_add']
    data5 = data5.reset_index()
    '''
    print('data5:',end='\n')
    print(data5.head(2),end='\n')
    print('GEO成功',end='\n')
    '''
############# Feature of UI################
    ####### Statistics
    #The number of times the user viewed the item
    data3['6_UI_useritemview'] = data3['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #The number of times the user collected the item
    data3['6_UI_useritemcollect'] = data3['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #The number of times the user carted the item
    data3['6_UI_useritemcart'] = data3['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    #The number of times the user purchased the item
    data3['6_UI_useritembuy'] = data3['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    ####### Ratio
    #The number of times the user views the item / The user's total views of all items
    data3['6_UI_useritemview_usertotalview'] = data3['6_UI_useritemview'] / data3['Number_of_acts_UI']
    #The number of times the user collects the item / The user's total collection of all items
    data3['6_UI_useritemcollect_usertotalcollect'] = data3['6_UI_useritemcollect'] / data3['Number_of_acts_UI']
    #The number of times the user carts the item / The user's total amount of all items added to the shopping cart
    data3['6_UI_useritemcart_usertotalcart'] = data3['6_UI_useritemcart'] / data3['Number_of_acts_UI']
    #The number of times the user purchases the item / The user's total purchases of all items
    data3['6_UI_useritembuy_usertotalbuy'] = data3['6_UI_useritembuy'] / data3['Number_of_acts_UI']
    data3 = data3.reset_index()
    '''
    print('data3:',end='\n')
    print(data3.head(2),end='\n')
    print('UI成功',end='\n')
    '''
#############Merge column#############
    df = pd.merge(df, data, how='left', on=['user_id'])
    df = pd.merge(df, data1, how='left', on=['item_id'])
    df = pd.merge(df, data5, how='left', on=['user_geohash1'])
    r_df= pd.merge(df, data3, how='left', on=['user_id', 'item_id'])
    print('success!!',end='\n')
    return r_df

In [14]:
for i in range(1,6):
    locals()['rr_df'+str(i)]=feature(locals()['df'+str(i)]) 
    print(locals()['rr_df'+str(i)].head(2),end='\n')
    locals()['col_df'+str(i)]= [x for x in locals()['rr_df'+str(i)].columns]
    print(locals()['col_df'+str(i)])

success!!
     user_id    item_id  behavior_type user_geohash  item_category  \
0  100029775   56574541              1          NaN           6689
1  100029775  287413918              1          NaN           5689

            time       time1 behavior_type1     user_id1     item_id1  ...  \
0  2014-12-16 12  2014-12-16            [1]  [100029775]   [56574541]  ...
1  2014-12-16 15  2014-12-16            [1]  [100029775]  [287413918]  ...

           Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0                 [1, 1]                 2                 2
1  [1, 1, 1, 1, 1, 1, 1]                 7                 7

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 0

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                              1.0                                    0.0
1                              1.0                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                            0.0
1                              0.0                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  220586551              1          NaN           7079

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-15 08  2014-12-15            [1]  [10001082]  [150720867]  ...
1  2014-12-14 03  2014-12-14            [1]  [10001082]  [220586551]  ...

  Behavior_list Number_of_acts_UI 6_UI_useritemview  6_UI_useritemcollect  \
0           [1]                 1                 1                     0
1  [1, 4, 1, 1]                 4                 3                     0

   6_UI_useritemcart  6_UI_useritembuy  6_UI_useritemview_usertotalview  \
0                  0                 0                             1.00
1                  0                 1                             0.75

   6_UI_useritemcollect_usertotalcollect  6_UI_useritemcart_usertotalcart  \
0                                    0.0                              0.0
1                                    0.0                              0.0

   6_UI_useritembuy_usertotalbuy
0                           0.00
1                           0.25

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  275221686              1          NaN          10576
1  10001082  220586551              1          NaN           7079

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-13 14  2014-12-13            [1]  [10001082]  [275221686]  ...
1  2014-12-14 03  2014-12-14            [1]  [10001082]  [220586551]  ...

                    Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]                10                10
1                    [1, 4, 1, 1]                 4                 3

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 1

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                             1.00                                    0.0
1                             0.75                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                           0.00
1                              0.0                           0.25

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  282931871              1          NaN           6000
1  10001082   62687596              1          NaN           6000

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-10 13  2014-12-10            [1]  [10001082]  [282931871]  ...
1  2014-12-10 13  2014-12-10            [1]  [10001082]   [62687596]  ...

  Behavior_list Number_of_acts_UI 6_UI_useritemview  6_UI_useritemcollect  \
0     [1, 1, 1]                 3                 3                     0
1        [1, 1]                 2                 2                     0

   6_UI_useritemcart  6_UI_useritembuy  6_UI_useritemview_usertotalview  \
0                  0                 0                              1.0
1                  0                 0                              1.0

   6_UI_useritemcollect_usertotalcollect  6_UI_useritemcart_usertotalcart  \
0                                    0.0                              0.0
1                                    0.0                              0.0

   6_UI_useritembuy_usertotalbuy
0                            0.0
1                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  275221686              1          NaN          10576
1  10001082     582649              1      95qobbk          12147

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-17 05  2014-12-17            [1]  [10001082]  [275221686]  ...
1  2014-12-17 18  2014-12-17            [1]  [10001082]     [582649]  ...

  Behavior_list Number_of_acts_UI 6_UI_useritemview  6_UI_useritemcollect  \
0        [1, 1]                 2                 2                     0
1           [1]                 1                 1                     0

   6_UI_useritemcart  6_UI_useritembuy  6_UI_useritemview_usertotalview  \
0                  0                 0                              1.0
1                  0                 0                              1.0

   6_UI_useritemcollect_usertotalcollect  6_UI_useritemcart_usertotalcart  \
0                                    0.0                              0.0
1                                    0.0                              0.0

   6_UI_useritembuy_usertotalbuy
0                            0.0
1                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

In [16]:
####Here you need to manually set the file path
loc = 'D:/Github/PHBS_MLF_2019/Data/Two Days/user_item_pair_'
train5= pd.read_excel(loc + 'test_form.xlsx')
train1234_1= pd.read_excel(loc + 'train_form.xlsx')
train5
train1234_1
'''
train5-18
train1234-11,15,16,17
'''
'''
train1_15,16,17
train2_14,15,16
train3_13,14,15
train4_9,10,11
test_16,17,18
'''

'\ntrain1_15,16,17\ntrain2_14,15,16\ntrain3_13,14,15\ntrain4_9,10,11\ntest_16,17,18\n'

In [17]:
train1234=train1234_1.reset_index()
train1234['id']=train1234['index']+1
train1234=train1234.drop(['index'],axis=1)
train1234.head(5)

   id    user_id    item_id  label        time
0   1  100029775   56574541      0  2014-12-17
1   2  100029775  287413918      0  2014-12-17
2   3  100029775  365811867      0  2014-12-17
3   4  100029775  297443044      0  2014-12-17
4   5  100029775  223294204      0  2014-12-17

In [18]:
#####The date needs to be set manually here
train1=train1234.loc[(train1234["time"]=="2014-12-17")]
train2=train1234.loc[(train1234["time"]=="2014-12-16")]
train3=train1234.loc[(train1234["time"]=="2014-12-15")]
train4=train1234.loc[(train1234["time"]=="2014-12-11")]
for i in range(1,5):
    print(locals()['train'+str(i)].head(2))

   id    user_id    item_id  label        time
0   1  100029775   56574541      0  2014-12-17
1   2  100029775  287413918      0  2014-12-17
    id    user_id    item_id  label        time
69  70  100029775  155889263      0  2014-12-16
70  71  100029775   17988661      0  2014-12-16
      id    user_id    item_id  label        time
141  142  100029775  287413918      0  2014-12-15
142  143  100029775  287413918      0  2014-12-15
      id    user_id    item_id  label        time
177  178  100029775   79140857      0  2014-12-11
178  179  100029775  239362693      0  2014-12-11

In [26]:
for i in range(1,6):
    locals()['df'+str(i)]=locals()['df'+str(i)].copy(deep=True)

#######match the columns of train/test with df
drop = ['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category',
            'time','time1', 'behavior_type1', 'user_id 1', 'user_id1','item_id1', 
            'user_item_pair', 'user_geohash1', 'Behavior_list_x','Behavior_list_y', 
            'Number_of_acts','behavior_total','behavior_list','Behavior_list', 'Number_of_acts_UI']

for i in range(1,6):
    locals()['train_col_'+str(i)]= [x for x in locals()['rr_df'+str(i)].columns if x not in drop]
    locals()['train'+str(i)][locals()['train_col_'+str(i)]] = locals()['rr_df'+str(i)][locals()['train_col_'+str(i)]]

In [27]:
train1_col= [x for x in train1.columns]
print(train1_col)

['id', 'user_id', 'item_id', 'label', 'time', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

In [28]:
train_1=train1.append([train2,train3,train4])
train_1=train_1.fillna(0)
train_1=train_1.replace(float('inf'),0)
train_2=train_1.sort_index(axis = 0,ascending = True,by = 'id')
train_2.head(10)

train5=train5.fillna(0)
train5=train5.replace(float('inf'),0)
test=train5
test

C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  after removing the cwd from sys.path.

,user_id,item_id,label,time,2_item_buy,2_item_view,2_item_collect,2_item_add,2_item_buy_view,2_item_buy_collect,...,4_geo_buy_collect,4_geo_buy_add,6_UI_useritemview,6_UI_useritemcollect,6_UI_useritemcart,6_UI_useritembuy,6_UI_useritemview_usertotalview,6_UI_useritemcollect_usertotalcollect,6_UI_useritemcart_usertotalcart,6_UI_useritembuy_usertotalbuy
0,10001082,275221686,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
1,10001082,582649,0,2014-12-18,0,4,0,0,0.000000,0.0,...,7.333333,0.666667,1,0,0,0,1.000000,0.000000,0.000000,0.000000
2,10001082,275221686,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
3,10001082,188586750,0,2014-12-18,0,4,0,0,0.000000,0.0,...,7.333333,0.666667,1,0,0,0,1.000000,0.000000,0.000000,0.000000
4,100029775,61251128,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,2,0,0,0,1.000000,0.000000,0.000000,0.000000
5,100029775,56574541,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
6,100029775,128989040,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,2,1,0,0,0.666667,0.333333,0.000000,0.000000
7,100029775,128989040,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,2,1,0,0,0.666667,0.333333,0.000000,0.000000
8,100029775,128989040,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,2,1,0,0,0.666667,0.333333,0.000000,0.000000
9,100029775,8021729,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,2,1,0,0,0.666667,0.333333,0.000000,0.000000
10,100029775,287413918,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
11,100029775,274868112,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,1,0,0,0.666667,0.333333,0.000000,0.000000
12,100029775,8021729,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,2,1,0,0,0.666667,0.333333,0.000000,0.000000
13,100029775,365811867,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
14,100029775,21968905,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,3,0,0,0,1.000000,0.000000,0.000000,0.000000
15,100029775,297443044,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
16,100029775,223294204,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
17,100029775,223294204,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
18,100029775,167854422,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,2,0,0,0,1.000000,0.000000,0.000000,0.000000
19,100029775,21968905,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,3,0,0,0,1.000000,0.000000,0.000000,0.000000
20,100029775,11803344,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
21,100029775,261875973,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
22,100029775,261875973,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
23,100029775,63698519,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,1,0,0,0.666667,0.333333,0.000000,0.000000
24,100029775,14815609,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
25,100029775,365811867,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
26,100029775,169159280,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
27,100029775,198524629,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.000000,0.000000,2,0,0,0,1.000000,0.000000,0.000000,0.000000
28,100029775,63698519,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,1,0,0,0.666667,0.333333,0.000000,0.000000
29,100029775,297443044,0,2014-12-18,0,43,6,0,0.000000,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65410,111694210,29708519,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,4,0,0,0,1.000000,0.000000,0.000000,0.000000
65411,111694210,181420737,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,1,0,0,0,1.000000,0.000000,0.000000,0.000000
65412,111694210,14040849,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65413,111694210,14040849,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65414,111694210,356269830,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.000000,0.500000,2,0,0,0,1.000000,0.000000,0.000000,0.000000
65415,111694210,255779389,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,1,0,0,0,1.000000,0.000000,0.000000,0.000000
65416,111694210,218933696,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,1,1,0.600000,0.000000,0.200000,0.200000
65417,111694210,33397549,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65418,111694210,248053725,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,5,0,1,1,0.714286,0.000000,0.142857,0.142857
65419,111694210,356943846,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,2,0,0,0,1.000000,0.000000,0.000000,0.000000
65420,111694210,356269830,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.000000,0.500000,2,0,0,0,1.000000,0.000000,0.000000,0.000000
65421,111694210,192152963,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,1,0,0,0,1.000000,0.000000,0.000000,0.000000
65422,111694210,298868867,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65423,111694210,16323036,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65424,111694210,16323036,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65425,111694210,302494770,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,1,1,0.600000,0.000000,0.200000,0.200000
65426,111694210,284382932,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,5,0,1,2,0.625000,0.000000,0.125000,0.250000
65427,111694210,128840093,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65428,111694210,116956856,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65429,111694210,396852821,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,1,0,0,0,1.000000,0.000000,0.000000,0.000000
65430,111694210,358656952,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,8,0,1,0,0.888889,0.000000,0.111111,0.000000
65431,111694210,170288789,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,1,0,0.750000,0.000000,0.250000,0.000000
65432,111694210,387365385,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,1,0,0,0,1.000000,0.000000,0.000000,0.000000
65433,111694210,84297505,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,7,0,1,2,0.700000,0.000000,0.100000,0.200000
65434,111694210,196280049,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,4,0,0,0,1.000000,0.000000,0.000000,0.000000
65435,111694210,262500385,0,2014-12-18,10,265,0,23,0.037736,0.0,...,0.473982,0.355990,3,0,0,0,1.000000,0.000000,0.000000,0.000000
65436,111699844,161189008,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.000000,0.000000,0.000000
65437,111699844,218673626,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.000000,0.000000,0.000000
65438,111699844,114740221,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.000000,0.000000,2,0,0,0,1.000000,0.000000,0.000000,0.000000
65439,111699844,114740221,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.000000,0.000000,2,0,0,0,1.000000,0.000000,0.000000,0.000000

In [29]:
train_2

,id,user_id,item_id,label,time,2_item_buy,2_item_view,2_item_collect,2_item_add,2_item_buy_view,...,4_geo_buy_collect,4_geo_buy_add,6_UI_useritemview,6_UI_useritemcollect,6_UI_useritemcart,6_UI_useritembuy,6_UI_useritemview_usertotalview,6_UI_useritemcollect_usertotalcollect,6_UI_useritemcart_usertotalcart,6_UI_useritembuy_usertotalbuy
0,1,100029775,56574541,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
1,2,100029775,287413918,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,7.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
2,3,100029775,365811867,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
3,4,100029775,297443044,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
4,5,100029775,223294204,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
5,6,100029775,223294204,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
6,7,100029775,11803344,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,3.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
7,8,100029775,63698519,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,1.0,0.0,0.0,0.666667,0.333333,0.0,0.0
8,9,100029775,365811867,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
9,10,100029775,169159280,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
10,11,100029775,63698519,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,1.0,0.0,0.0,0.666667,0.333333,0.0,0.0
11,12,100029775,297443044,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
12,13,100029775,63698519,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,1.0,0.0,0.0,0.666667,0.333333,0.0,0.0
13,14,100029775,11803344,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,3.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
14,15,100029775,205052614,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,1.0,0.0,0.0,0.666667,0.333333,0.0,0.0
15,16,100029775,205052614,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,1.0,0.0,0.0,0.666667,0.333333,0.0,0.0
16,17,100029775,205052614,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,1.0,0.0,0.0,0.666667,0.333333,0.0,0.0
17,18,100029775,11803344,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,3.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
18,19,100029775,56574541,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
19,20,100029775,169159280,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
20,21,100029775,287413918,0,2014-12-17,0.0,67.0,2.0,0.0,0.0,...,0.468974,0.331366,7.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
21,22,100029775,155889263,0,2014-12-17,0.0,43.0,1.0,3.0,0.0,...,0.000000,0.000000,3.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
22,23,100029775,17988661,0,2014-12-17,0.0,63.0,0.0,0.0,0.0,...,0.468974,0.331366,1.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
23,24,100029775,32720344,0,2014-12-17,0.0,63.0,0.0,0.0,0.0,...,0.468974,0.331366,6.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
24,25,100029775,350942199,0,2014-12-17,0.0,63.0,0.0,0.0,0.0,...,0.468974,0.331366,3.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
25,26,100029775,287413918,0,2014-12-17,0.0,63.0,0.0,0.0,0.0,...,0.468974,0.331366,3.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
26,27,100029775,210028911,0,2014-12-17,0.0,63.0,0.0,0.0,0.0,...,0.468974,0.331366,3.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
27,28,100029775,130639998,0,2014-12-17,0.0,63.0,0.0,0.0,0.0,...,0.468974,0.331366,3.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
28,29,100029775,230835230,0,2014-12-17,0.0,63.0,0.0,0.0,0.0,...,0.468974,0.331366,1.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
29,30,100029775,49063582,0,2014-12-17,0.0,63.0,0.0,0.0,0.0,...,0.468974,0.331366,2.0,0.0,0.0,0.0,1.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279495,279496,110030137,270735438,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279496,279497,110030137,189424898,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279497,279498,110030137,385284377,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279498,279499,110030137,345020639,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279499,279500,110030137,300110151,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279500,279501,110030137,90887254,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279501,279502,110030137,219690249,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279502,279503,110030137,237026804,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279503,279504,110030137,126814128,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279504,279505,110030137,90887254,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279505,279506,110030137,126814128,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279506,279507,110241664,343877187,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279507,279508,110241664,114188162,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279508,279509,110241664,114188162,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279509,279510,110241664,114188162,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279510,279511,110653123,398325724,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279511,279512,110653123,146981047,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279512,279513,110653123,146981047,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279513,279514,110653123,146981047,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279514,279515,110653123,301395506,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279515,279516,110653123,398325724,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279516,279517,110653123,396609803,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279517,279518,110653123,396609803,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279518,279519,110653123,301395506,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279519,279520,110653123,146981047,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279520,279521,110653123,260992925,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279521,279522,111609133,153571485,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279522,279523,111609133,290347011,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279523,279524,111609133,290347011,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
279524,279525,111609133,153571485,0,2014-12-11,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0

In [ ]:
train_2.to_excel('D:/Github/PHBS_MLF_2019/Data/Two Days/result/user_item_pair_train_XCQ.xlsx')

In [ ]:
test.to_excel('D:/Github/PHBS_MLF_2019/Data/Two Days/result/user_item_pair_test_XCQ.xlsx')

# Data-3days

In [1]:
from threading import Thread
import pandas as pd
from collections import Counter
import  numpy as np

In [6]:
loc = 'D:/Github/PHBS_MLF_2019/Data/Three Days/tianchi_fresh_comp_train_user_'
df1_1= pd.read_excel(loc + 'train1.xlsx')
df1_2= pd.read_excel(loc + 'train2.xlsx')
df1_3= pd.read_excel(loc + 'train3.xlsx')
df1_4= pd.read_excel(loc + 'train4.xlsx')
df1_5= pd.read_excel(loc + 'test.xlsx')
'''
train1_14,15,16,17
train2_13,14,15,16
train3_8,9,10,11
train4_7,8,9,10
test_15,16,17,18
'''

'\ntrain1_14,15,16,17\ntrain2_13,14,15,16\ntrain3_8,9,10,11\ntrain4_7,8,9,10\ntest_15,16,17,18\n'

In [9]:
for i in range(1,6):
    locals()['df1_'+str(i)]['time1']=locals()['df1_'+str(i)]['time'].map(lambda x:x.split(" ")[0])

df1=df1_1.loc[(df1_1["time1"]!="2014-12-17")]
df2=df1_2.loc[(df1_2["time1"]!="2014-12-16")]
df3=df1_3.loc[(df1_3["time1"]!="2014-12-11")]
df4=df1_4.loc[(df1_4["time1"]!="2014-12-10")]
df5=df1_5.loc[(df1_5["time1"]!="2014-12-18")]

for i in range(1,6):
    print(locals()['df'+str(i)].head())

    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  220586551              1          NaN           7079
2  10001082  209290607              1          NaN           5894
3  10001082   22667958              1      95qogn4          10523
4  10001082  125083630              1          NaN           4722

            time       time1
0  2014-12-15 08  2014-12-15
1  2014-12-14 03  2014-12-14
2  2014-12-14 16  2014-12-14
3  2014-12-15 08  2014-12-15
4  2014-12-14 03  2014-12-14
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  275221686              1          NaN          10576
2  10001082  220586551              1          NaN           7079
3  10001082  209290607              1          NaN           5894
4  10001082   22667958              1      95qogn4          10523

            time       time1
0  2014-12-15 08  2014-12-15
1  2014-12-13 14  2014-12-13
2  2014-12-14 03  2014-12-14
3  2014-12-14 16  2014-12-14
4  2014-12-15 08  2014-12-15
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576
2  10001082  236453039              1          NaN          10576
3  10001082  282931871              1          NaN           6000
4  10001082  275221686              1          NaN          10576

            time       time1
0  2014-12-08 18  2014-12-08
1  2014-12-08 07  2014-12-08
2  2014-12-08 07  2014-12-08
3  2014-12-10 13  2014-12-10
4  2014-12-08 07  2014-12-08
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576
2  10001082  236453039              1          NaN          10576
4  10001082  275221686              1          NaN          10576
5  10001082  275221686              1          NaN          10576

            time       time1
0  2014-12-08 18  2014-12-08
1  2014-12-08 07  2014-12-08
2  2014-12-08 07  2014-12-08
4  2014-12-08 07  2014-12-08
5  2014-12-08 00  2014-12-08
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082   22667958              1      95qogn4          10523
2  10001082  133020432              1      95qog2a           3200
3  10001082  275221686              1          NaN          10576
4  10001082     582649              1      95qobbk          12147

            time       time1
0  2014-12-15 08  2014-12-15
1  2014-12-15 08  2014-12-15
2  2014-12-15 08  2014-12-15
3  2014-12-17 05  2014-12-17
4  2014-12-17 18  2014-12-17

In [10]:
for i in range(1,6):
    locals()['df'+str(i)]=locals()['df'+str(i)].copy(deep=True)

def feature(df):
    df['behavior_type1']=df['behavior_type'].apply(lambda x: list(str(x)))
    df['user_id1'] = df['user_id'].apply(lambda x: [str(x)])
    df['item_id1'] = df['item_id'].apply(lambda x: [str(x)])
    df['user_item_pair']=df['user_id'].map(str)+'-'+df['item_id'].map(str)
    df['user_geohash1'] = df['user_geohash'].apply(lambda x: 0 if x=='nan' else str(x)[:3])
    #groupby
    a = df.groupby('user_id')['behavior_type1'].sum()
    b = df.groupby('item_id')['behavior_type1'].sum()
    c = df.groupby('item_id')['user_id1'].sum()
    d=df.groupby(['user_id','item_id'])['behavior_type1'].sum()
    e=df.groupby(['user_id','item_id'])['item_id1'].sum()
    f= df.groupby('user_geohash1')['behavior_type1'].sum()
    data = pd.DataFrame()
    data['Behavior_list'] = a
    data1 = pd.DataFrame()
    data1['Behavior_list'] = b
    data2 = pd.DataFrame()
    data2['user_id_list'] = c
    data3=pd.DataFrame()
    data3['Behavior_list']=d
    data4=pd.DataFrame()
    data4['item_id_list']=e 
    data5 = pd.DataFrame()
    data5['behavior_list'] = f
    # count the number of acts of each group
    data1['Number_of_acts'] = data2['user_id_list'].apply(lambda x: len(x))
    data3['Number_of_acts_UI'] = data4['item_id_list'].apply(lambda x: len(x))
    '''
    print('data1:',end='\n')
    print(data1.head(2),end='\n')
    print('data3:',end='\n')
    print(data3.head(2),end='\n')
    '''
############# Feature of item################
####### Statistics
    #Number of times the product was purchased
    data['2_item_buy'] = data['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    #Number of users who purchased the item
    data1['2_item_buypeople'] = data1['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    #Number of times the product was viewed
    data['2_item_view'] = data['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #Number of users who viewed the item
    data1['2_item_viewpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #Number of times the product was collected
    data['2_item_collect'] = data['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #Number of users who collected the item
    data1['2_item_collectpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #Number of times the product was carted
    data['2_item_add'] = data['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    # Number of users who carted the item
    data1['2_item_addpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])

####### Ratio
    #Number of times the product was purchased/Number of times the product was viewed
    data['2_item_buy_view'] = data['2_item_buy']/data['2_item_view']
    #Number of users who purchased the item/Number of users who viewed the item
    data1['2_item_buypeople_viewpeople'] = data1['2_item_buypeople']/data1['2_item_viewpeople']
    #Number of times the product was purchased/Number of times the product was collected
    data['2_item_buy_collect'] = data['2_item_buy'] / data['2_item_collect']
    #Number of users who purchased the item/Number of users who collected the item
    data1['2_item_buypeople_collectpeople'] = data1['2_item_buypeople']/data1['2_item_collectpeople']
    #Number of times the product was purchased/Number of times the product was carted
    data['2_item_buy_add'] = data['2_item_buy'] / data['2_item_add']
    #Number of users who purchased the item/Number of users who carted the item
    data1['2_item_buypeople_addpeople'] = data1['2_item_buypeople']/data1['2_item_addpeople']
    #Number of users who make multiple purchases/Number of users who purchased the product in the two days
    data1['2_item_frequentbuypeople_buypeople'] = data1['2_item_buypeople'] / data1['Number_of_acts']
    #Number of users who viewed the product multiple times/Number of users who purchased the product in the two days
    data1['2_item_frequentviewpeople_viewpeople'] = data1['2_item_viewpeople'] / data1['Number_of_acts']
    #Number of users who collected the product multiple times/Number of users who purchased the product in the two days 
    data1['2_item_frequentcollectpeople_collectpeople'] = data1['2_item_collectpeople'] / data1['Number_of_acts']
    #Number of users who carted the product multiple times/Number of users who purchased the product in the two days
    data1['2_item_frequentaddpeople_addpeople'] = data1['2_item_addpeople'] / data1['Number_of_acts']
    data = data.reset_index()
    data1 = data1.reset_index()
    '''
    print('data:',end='\n')
    print(data.head(2),end='\n')
    print('data1:',end='\n')
    print(data1.head(2),end='\n')
    print('item成功',end='\n')
    '''
############# Feature of GEO(geographic location)################
    data5['4_geo_view'] = data5['behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    data5['4_geo_collect'] = data5['behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    data5['4_geo_add'] = data5['behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    data5['4_geo_buy'] = data5['behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    data5['behavior_total'] = data5['behavior_list'].apply(lambda x: len(x))
    #Number of items purchased in the area / Total number of users in the area
    data5['4_geo_purchasepower'] = data5['4_geo_buy']/data5['behavior_total']
    #Number of items purchased in the area / Number of goods viewed in the area
    data5['4_geo_buy_view'] = data5['4_geo_buy']/data5['4_geo_view']
    #Number of goods purchased in the area / Number of goods collected in the area   
    data5['4_geo_buy_collect'] = data5['4_geo_buy']/data5['4_geo_collect']
    #Number of goods purchased in the area to / Number of goods carted in the area    
    data5['4_geo_buy_add'] = data5['4_geo_buy']/data5['4_geo_add']
    data5 = data5.reset_index()
    '''
    print('data5:',end='\n')
    print(data5.head(2),end='\n')
    print('GEO成功',end='\n')
    '''
############# Feature of UI################
    ####### Statistics
    #The number of times the user viewed the item
    data3['6_UI_useritemview'] = data3['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #The number of times the user collected the item
    data3['6_UI_useritemcollect'] = data3['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #The number of times the user carted the item
    data3['6_UI_useritemcart'] = data3['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    #The number of times the user purchased the item
    data3['6_UI_useritembuy'] = data3['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    ####### Ratio
    #The number of times the user views the item / The user's total views of all items
    data3['6_UI_useritemview_usertotalview'] = data3['6_UI_useritemview'] / data3['Number_of_acts_UI']
    #The number of times the user collects the item / The user's total collection of all items
    data3['6_UI_useritemcollect_usertotalcollect'] = data3['6_UI_useritemcollect'] / data3['Number_of_acts_UI']
    #The number of times the user carts the item / The user's total amount of all items added to the shopping cart
    data3['6_UI_useritemcart_usertotalcart'] = data3['6_UI_useritemcart'] / data3['Number_of_acts_UI']
    #The number of times the user purchases the item / The user's total purchases of all items
    data3['6_UI_useritembuy_usertotalbuy'] = data3['6_UI_useritembuy'] / data3['Number_of_acts_UI']
    data3 = data3.reset_index()
    '''
    print('data3:',end='\n')
    print(data3.head(2),end='\n')
    print('UI成功',end='\n')
    '''
#############Merge column#############
    df = pd.merge(df, data, how='left', on=['user_id'])
    df = pd.merge(df, data1, how='left', on=['item_id'])
    df = pd.merge(df, data5, how='left', on=['user_geohash1'])
    r_df= pd.merge(df, data3, how='left', on=['user_id', 'item_id'])
    print('success!!',end='\n')
    return r_df

In [11]:
for i in range(1,6):
    locals()['rr_df'+str(i)]=feature(locals()['df'+str(i)]) 
    print(locals()['rr_df'+str(i)].head(2),end='\n')
    locals()['col_df'+str(i)]= [x for x in locals()['rr_df'+str(i)].columns]
    print(locals()['col_df'+str(i)])

success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  220586551              1          NaN           7079

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-15 08  2014-12-15            [1]  [10001082]  [150720867]  ...
1  2014-12-14 03  2014-12-14            [1]  [10001082]  [220586551]  ...

  Behavior_list Number_of_acts_UI 6_UI_useritemview  6_UI_useritemcollect  \
0           [1]                 1                 1                     0
1  [1, 4, 1, 1]                 4                 3                     0

   6_UI_useritemcart  6_UI_useritembuy  6_UI_useritemview_usertotalview  \
0                  0                 0                             1.00
1                  0                 1                             0.75

   6_UI_useritemcollect_usertotalcollect  6_UI_useritemcart_usertotalcart  \
0                                    0.0                              0.0
1                                    0.0                              0.0

   6_UI_useritembuy_usertotalbuy
0                           0.00
1                           0.25

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  275221686              1          NaN          10576

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-15 08  2014-12-15            [1]  [10001082]  [150720867]  ...
1  2014-12-13 14  2014-12-13            [1]  [10001082]  [275221686]  ...

                          Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0                                   [1]                 1                 1
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]                12                12

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 0

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                              1.0                                    0.0
1                              1.0                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                            0.0
1                              0.0                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-08 18  2014-12-08            [1]  [10001082]  [285259775]  ...
1  2014-12-08 07  2014-12-08            [1]  [10001082]  [275221686]  ...

        Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0                 [1]                 1                 1
1  [1, 1, 1, 1, 1, 1]                 6                 6

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 0

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                              1.0                                    0.0
1                              1.0                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                            0.0
1                              0.0                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-08 18  2014-12-08            [1]  [10001082]  [285259775]  ...
1  2014-12-08 07  2014-12-08            [1]  [10001082]  [275221686]  ...

                 Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0                          [1]                 1                 1
1  [1, 1, 1, 1, 1, 1, 1, 1, 1]                 9                 9

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 0

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                              1.0                                    0.0
1                              1.0                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                            0.0
1                              0.0                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082   22667958              1      95qogn4          10523

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-15 08  2014-12-15            [1]  [10001082]  [150720867]  ...
1  2014-12-15 08  2014-12-15            [1]  [10001082]   [22667958]  ...

  Behavior_list Number_of_acts_UI 6_UI_useritemview  6_UI_useritemcollect  \
0           [1]                 1                 1                     0
1     [1, 1, 1]                 3                 3                     0

   6_UI_useritemcart  6_UI_useritembuy  6_UI_useritemview_usertotalview  \
0                  0                 0                              1.0
1                  0                 0                              1.0

   6_UI_useritemcollect_usertotalcollect  6_UI_useritemcart_usertotalcart  \
0                                    0.0                              0.0
1                                    0.0                              0.0

   6_UI_useritembuy_usertotalbuy
0                            0.0
1                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

In [30]:
####Here you need to manually set the file path
loc = 'D:/Github/PHBS_MLF_2019/Data/Three Days/user_item_pair_'
train5= pd.read_excel(loc + 'test_form.xlsx')
train1234_1= pd.read_excel(loc + 'train_form.xlsx')
train5
train1234_1
'''
train5-18
train1234-10,11,16,17
'''
'''
train1_14,15,16,17
train2_13,14,15,16
train3_8,9,10,11
train4_7,8,9,10
test_15,16,17,18
'''

'\ntrain1_14,15,16,17\ntrain2_13,14,15,16\ntrain3_8,9,10,11\ntrain4_7,8,9,10\ntest_15,16,17,18\n'

In [33]:
train1234=train1234_1.reset_index()
train1234['id']=train1234['index']+1
train1234=train1234.drop(['index'],axis=1)
train1234.head(5)

   id   user_id    item_id  label        time
0   1  10001082  150720867      0  2014-12-17
1   2  10001082  220586551      0  2014-12-17
2   3  10001082  209290607      0  2014-12-17
3   4  10001082   22667958      0  2014-12-17
4   5  10001082  125083630      0  2014-12-17

In [35]:
#####The date needs to be set manually here
train1=train1234.loc[(train1234["time"]=="2014-12-17")]
train2=train1234.loc[(train1234["time"]=="2014-12-16")]
train3=train1234.loc[(train1234["time"]=="2014-12-11")]
train4=train1234.loc[(train1234["time"]=="2014-12-10")]
for i in range(1,5):
    print(locals()['train'+str(i)].head(2))

   id   user_id    item_id  label        time
0   1  10001082  150720867      0  2014-12-17
1   2  10001082  220586551      0  2014-12-17
    id   user_id    item_id  label        time
30  31  10001082  150720867      0  2014-12-16
31  32  10001082  275221686      0  2014-12-16
    id   user_id    item_id  label        time
79  80  10001082  285259775      0  2014-12-11
80  81  10001082  275221686      0  2014-12-11
      id   user_id    item_id  label        time
111  112  10001082  285259775      0  2014-12-10
112  113  10001082  275221686      0  2014-12-10

In [36]:
for i in range(1,6):
    locals()['df'+str(i)]=locals()['df'+str(i)].copy(deep=True)

#######match the columns of train/test with df
drop = ['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category',
            'time','time1', 'behavior_type1', 'user_id 1', 'user_id1','item_id1', 
            'user_item_pair', 'user_geohash1', 'Behavior_list_x','Behavior_list_y', 
            'Number_of_acts','behavior_total','behavior_list','Behavior_list', 'Number_of_acts_UI']

for i in range(1,6):
    locals()['train_col_'+str(i)]= [x for x in locals()['rr_df'+str(i)].columns if x not in drop]
    locals()['train'+str(i)][locals()['train_col_'+str(i)]] = locals()['rr_df'+str(i)][locals()['train_col_'+str(i)]]

In [37]:
train1_col= [x for x in train1.columns]
print(train1_col)

['id', 'user_id', 'item_id', 'label', 'time', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

In [44]:
train_1=train1.append([train2,train3,train4])
train_1=train_1.fillna(0)
train_1=train_1.replace(float('inf'),0)
train_2=train_1.sort_index(axis = 0,ascending = True,by = 'id')
train_2.head(10)

train5=train5.fillna(0)
train5=train5.replace(float('inf'),0)
test=train5
test

C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  after removing the cwd from sys.path.

,user_id,item_id,label,time,2_item_buy,2_item_view,2_item_collect,2_item_add,2_item_buy_view,2_item_buy_collect,...,4_geo_buy_collect,4_geo_buy_add,6_UI_useritemview,6_UI_useritemcollect,6_UI_useritemcart,6_UI_useritembuy,6_UI_useritemview_usertotalview,6_UI_useritemcollect_usertotalcollect,6_UI_useritemcart_usertotalcart,6_UI_useritembuy_usertotalbuy
0,10001082,150720867,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,1,0,0,0,1.000000,0.000000,0.000000,0.00
1,10001082,22667958,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,3,0,0,0,1.000000,0.000000,0.000000,0.00
2,10001082,133020432,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,1,0,0,0,1.000000,0.000000,0.000000,0.00
3,10001082,275221686,0,2014-12-18,0,13,0,0,0.000000,0.0,...,0.47806,0.357102,4,0,0,0,1.000000,0.000000,0.000000,0.00
4,10001082,582649,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,1,0,0,0,1.000000,0.000000,0.000000,0.00
5,10001082,377161387,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,2,0,0,0,1.000000,0.000000,0.000000,0.00
6,10001082,275221686,0,2014-12-18,0,13,0,0,0.000000,0.0,...,0.47806,0.357102,4,0,0,0,1.000000,0.000000,0.000000,0.00
7,10001082,275221686,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,4,0,0,0,1.000000,0.000000,0.000000,0.00
8,10001082,275221686,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,4,0,0,0,1.000000,0.000000,0.000000,0.00
9,10001082,22667958,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,3,0,0,0,1.000000,0.000000,0.000000,0.00
10,10001082,22667958,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,3,0,0,0,1.000000,0.000000,0.000000,0.00
11,10001082,377161387,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,2,0,0,0,1.000000,0.000000,0.000000,0.00
12,10001082,188586750,0,2014-12-18,0,13,0,0,0.000000,0.0,...,21.00000,0.940299,1,0,0,0,1.000000,0.000000,0.000000,0.00
13,100029775,61251128,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,2,0,0,0,1.000000,0.000000,0.000000,0.00
14,100029775,56574541,0,2014-12-18,0,91,6,0,0.000000,0.0,...,0.47806,0.357102,2,0,0,0,1.000000,0.000000,0.000000,0.00
15,100029775,128989040,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,2,1,0,0,0.666667,0.333333,0.000000,0.00
16,100029775,128989040,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,2,1,0,0,0.666667,0.333333,0.000000,0.00
17,100029775,128989040,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,2,1,0,0,0.666667,0.333333,0.000000,0.00
18,100029775,155889263,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,2,0,0,0,1.000000,0.000000,0.000000,0.00
19,100029775,17988661,0,2014-12-18,0,91,6,0,0.000000,0.0,...,0.47806,0.357102,8,0,0,0,1.000000,0.000000,0.000000,0.00
20,100029775,32720344,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,2,0,0,0,1.000000,0.000000,0.000000,0.00
21,100029775,8021729,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,2,1,0,0,0.666667,0.333333,0.000000,0.00
22,100029775,287413918,0,2014-12-18,0,91,6,0,0.000000,0.0,...,0.47806,0.357102,7,0,0,0,1.000000,0.000000,0.000000,0.00
23,100029775,274868112,0,2014-12-18,0,91,6,0,0.000000,0.0,...,0.47806,0.357102,2,1,0,0,0.666667,0.333333,0.000000,0.00
24,100029775,8021729,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,2,1,0,0,0.666667,0.333333,0.000000,0.00
25,100029775,350942199,0,2014-12-18,0,91,6,0,0.000000,0.0,...,0.47806,0.357102,2,0,0,0,1.000000,0.000000,0.000000,0.00
26,100029775,365811867,0,2014-12-18,0,91,6,0,0.000000,0.0,...,0.47806,0.357102,2,0,0,0,1.000000,0.000000,0.000000,0.00
27,100029775,21968905,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,3,0,0,0,1.000000,0.000000,0.000000,0.00
28,100029775,287413918,0,2014-12-18,0,91,6,0,0.000000,0.0,...,1.00000,1.000000,7,0,0,0,1.000000,0.000000,0.000000,0.00
29,100029775,210028911,0,2014-12-18,0,91,6,0,0.000000,0.0,...,0.47806,0.357102,3,0,0,0,1.000000,0.000000,0.000000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99405,111694210,356943846,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,2,0,0,0,1.000000,0.000000,0.000000,0.00
99406,111694210,356269830,0,2014-12-18,11,357,0,25,0.030812,0.0,...,9.00000,0.360000,2,0,0,0,1.000000,0.000000,0.000000,0.00
99407,111694210,192152963,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,1,0,0,0,1.000000,0.000000,0.000000,0.00
99408,111694210,298868867,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,0,0,1.000000,0.000000,0.000000,0.00
99409,111694210,16323036,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,0,0,1.000000,0.000000,0.000000,0.00
99410,111694210,16323036,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,0,0,1.000000,0.000000,0.000000,0.00
99411,111694210,302494770,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,1,1,0.600000,0.000000,0.200000,0.20
99412,111694210,284382932,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,5,0,1,2,0.625000,0.000000,0.125000,0.25
99413,111694210,57406974,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,2,0,0,0,1.000000,0.000000,0.000000,0.00
99414,111694210,128840093,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,0,0,1.000000,0.000000,0.000000,0.00
99415,111694210,189948372,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,1,0,0,0,1.000000,0.000000,0.000000,0.00
99416,111694210,386095395,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,0,0,1.000000,0.000000,0.000000,0.00
99417,111694210,116956856,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,0,0,1.000000,0.000000,0.000000,0.00
99418,111694210,396852821,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,1,0,0,0,1.000000,0.000000,0.000000,0.00
99419,111694210,365758597,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,0,0,1.000000,0.000000,0.000000,0.00
99420,111694210,358656952,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,8,0,1,0,0.888889,0.000000,0.111111,0.00
99421,111694210,313337652,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,2,0,0,0,1.000000,0.000000,0.000000,0.00
99422,111694210,62423278,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,2,0,1,0,0.666667,0.000000,0.333333,0.00
99423,111694210,57406974,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,2,0,0,0,1.000000,0.000000,0.000000,0.00
99424,111694210,306811335,0,2014-12-18,11,357,0,25,0.030812,0.0,...,9.00000,0.360000,5,0,0,0,1.000000,0.000000,0.000000,0.00
99425,111694210,170288789,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,3,0,1,0,0.750000,0.000000,0.250000,0.00
99426,111694210,387365385,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,1,0,0,0,1.000000,0.000000,0.000000,0.00
99427,111694210,136711536,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,2,0,0,0,1.000000,0.000000,0.000000,0.00
99428,111694210,84297505,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,7,0,1,2,0.700000,0.000000,0.100000,0.20
99429,111694210,196280049,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,4,0,0,0,1.000000,0.000000,0.000000,0.00
99430,111694210,262500385,0,2014-12-18,11,357,0,25,0.030812,0.0,...,0.47806,0.357102,6,0,0,0,1.000000,0.000000,0.000000,0.00
99431,111699844,161189008,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.00000,0.000000,1,0,0,0,1.000000,0.000000,0.000000,0.00
99432,111699844,218673626,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.00000,0.000000,1,0,0,0,1.000000,0.000000,0.000000,0.00
99433,111699844,114740221,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.00000,0.000000,2,0,0,0,1.000000,0.000000,0.000000,0.00
99434,111699844,114740221,0,2014-12-18,0,4,0,0,0.000000,0.0,...,0.00000,0.000000,2,0,0,0,1.000000,0.000000,0.000000,0.00

In [45]:
train_2

,id,user_id,item_id,label,time,2_item_buy,2_item_view,2_item_collect,2_item_add,2_item_buy_view,...,4_geo_buy_collect,4_geo_buy_add,6_UI_useritemview,6_UI_useritemcollect,6_UI_useritemcart,6_UI_useritembuy,6_UI_useritemview_usertotalview,6_UI_useritemcollect_usertotalcollect,6_UI_useritemcart_usertotalcart,6_UI_useritembuy_usertotalbuy
0,1,10001082,150720867,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
1,2,10001082,220586551,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,3.0,0.0,0.0,1.0,0.75,0.0,0.0,0.25
2,3,10001082,209290607,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
3,4,10001082,22667958,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
4,5,10001082,125083630,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
5,6,10001082,133020432,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
6,7,10001082,377161387,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,2.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
7,8,10001082,110790001,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
8,9,10001082,220586551,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,3.0,0.0,0.0,1.0,0.75,0.0,0.0,0.25
9,10,10001082,85851739,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
10,11,10001082,278017344,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
11,12,10001082,85851739,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
12,13,10001082,275221686,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
13,14,10001082,282816229,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
14,15,10001082,6862367,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
15,16,10001082,275221686,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
16,17,10001082,345696502,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
17,18,10001082,275221686,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
18,19,10001082,85851739,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
19,20,10001082,22667958,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
20,21,10001082,336390925,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
21,22,10001082,220586551,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,3.0,0.0,0.0,1.0,0.75,0.0,0.0,0.25
22,23,10001082,220586551,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,3.0,0.0,0.0,1.0,0.75,0.0,0.0,0.25
23,24,10001082,22667958,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
24,25,10001082,377161387,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.000000,0.393204,2.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
25,26,10001082,399970059,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
26,27,10001082,336390925,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
27,28,10001082,336390925,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
28,29,10001082,275221686,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
29,30,10001082,85851739,0,2014-12-17,1.0,29.0,0.0,0.0,0.034483,...,0.491037,0.356335,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420881,420882,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420882,420883,110973556,7046626,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420883,420884,110973556,30986052,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420884,420885,110973556,30986052,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420885,420886,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420886,420887,110973556,311406606,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420887,420888,110973556,125731763,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420888,420889,110973556,52457625,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420889,420890,110973556,348755836,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420890,420891,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420891,420892,110973556,228404111,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420892,420893,110973556,125731763,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420893,420894,110973556,134633361,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420894,420895,110973556,30986052,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420895,420896,110973556,215595408,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420896,420897,110973556,228404111,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420897,420898,110973556,233988483,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420898,420899,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420899,420900,110973556,271469277,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420900,420901,110973556,125731763,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420901,420902,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420902,420903,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420903,420904,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420904,420905,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420905,420906,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420906,420907,110973556,295843293,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420907,420908,110973556,52457625,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420908,420909,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420909,420910,110973556,321976643,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
420910,420911,110973556,190614692,0,2014-12-10,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00

In [ ]:
train_2.to_excel('D:/Github/PHBS_MLF_2019/Data/Four Days/result/user_item_pair_train_XCQ.xlsx')

In [ ]:
test.to_excel('D:/Github/PHBS_MLF_2019/Data/Four Days/result/user_item_pair_test_XCQ.xlsx')

# Data-4 days

In [30]:
loc = 'D:/Github/PHBS_MLF_2019/Data/Four Days/tianchi_fresh_comp_train_user_'
df1_1= pd.read_excel(loc + 'train1.xlsx')
df1_2= pd.read_excel(loc + 'train2.xlsx')
df1_3= pd.read_excel(loc + 'train3.xlsx')
df1_4= pd.read_excel(loc + 'train4.xlsx')
df1_5= pd.read_excel(loc + 'test.xlsx')
'''
train1_13,14,15,16,17
train2_7,8,9,10,11
train3_6,7,8,9,10
train4_5,6,7,8,9
test_14,15,16,17,18
'''

'\ntrain1_13,14,15,16,17\ntrain2_7,8,9,10,11\ntrain3_6,7,8,9,10\ntrain4_5,6,7,8,9\ntest_14,15,16,17,18\n'

In [31]:
for i in range(1,6):
    locals()['df1_'+str(i)]['time1']=locals()['df1_'+str(i)]['time'].map(lambda x:x.split(" ")[0])

df1=df1_1.loc[(df1_1["time1"]!="2014-12-17")]
df2=df1_2.loc[(df1_2["time1"]!="2014-12-11")]
df3=df1_3.loc[(df1_3["time1"]!="2014-12-10")]
df4=df1_4.loc[(df1_4["time1"]!="2014-12-09")]
df5=df1_5.loc[(df1_5["time1"]!="2014-12-18")]

for i in range(1,6):
    print(locals()['df'+str(i)].head())

    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  275221686              1          NaN          10576
2  10001082  220586551              1          NaN           7079
3  10001082  209290607              1          NaN           5894
4  10001082   22667958              1      95qogn4          10523

            time       time1
0  2014-12-15 08  2014-12-15
1  2014-12-13 14  2014-12-13
2  2014-12-14 03  2014-12-14
3  2014-12-14 16  2014-12-14
4  2014-12-15 08  2014-12-15
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576
2  10001082  236453039              1          NaN          10576
3  10001082  282931871              1          NaN           6000
4  10001082  275221686              1          NaN          10576

            time       time1
0  2014-12-08 18  2014-12-08
1  2014-12-08 07  2014-12-08
2  2014-12-08 07  2014-12-08
3  2014-12-10 13  2014-12-10
4  2014-12-08 07  2014-12-08
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576
2  10001082  236453039              1          NaN          10576
4  10001082  275221686              1          NaN          10576
5  10001082  275221686              1          NaN          10576

            time       time1
0  2014-12-08 18  2014-12-08
1  2014-12-08 07  2014-12-08
2  2014-12-08 07  2014-12-08
4  2014-12-08 07  2014-12-08
5  2014-12-08 00  2014-12-08
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576
2  10001082  236453039              1          NaN          10576
3  10001082  275221686              1          NaN          10576
4  10001082  275221686              1          NaN          10576

            time       time1
0  2014-12-08 18  2014-12-08
1  2014-12-08 07  2014-12-08
2  2014-12-08 07  2014-12-08
3  2014-12-08 07  2014-12-08
4  2014-12-08 00  2014-12-08
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  220586551              1          NaN           7079
2  10001082  209290607              1          NaN           5894
3  10001082   22667958              1      95qogn4          10523
4  10001082  125083630              1          NaN           4722

            time       time1
0  2014-12-15 08  2014-12-15
1  2014-12-14 03  2014-12-14
2  2014-12-14 16  2014-12-14
3  2014-12-15 08  2014-12-15
4  2014-12-14 03  2014-12-14

In [34]:
for i in range(1,6):
    locals()['df'+str(i)]=locals()['df'+str(i)].copy(deep=True)

def feature(df):
    df['behavior_type1']=df['behavior_type'].apply(lambda x: list(str(x)))
    df['user_id1'] = df['user_id'].apply(lambda x: [str(x)])
    df['item_id1'] = df['item_id'].apply(lambda x: [str(x)])
    df['user_item_pair']=df['user_id'].map(str)+'-'+df['item_id'].map(str)
    df['user_geohash1'] = df['user_geohash'].apply(lambda x: 0 if x=='nan' else str(x)[:3])
    #groupby
    a = df.groupby('user_id')['behavior_type1'].sum()
    b = df.groupby('item_id')['behavior_type1'].sum()
    c = df.groupby('item_id')['user_id1'].sum()
    d=df.groupby(['user_id','item_id'])['behavior_type1'].sum()
    e=df.groupby(['user_id','item_id'])['item_id1'].sum()
    f= df.groupby('user_geohash1')['behavior_type1'].sum()
    data = pd.DataFrame()
    data['Behavior_list'] = a
    data1 = pd.DataFrame()
    data1['Behavior_list'] = b
    data2 = pd.DataFrame()
    data2['user_id_list'] = c
    data3=pd.DataFrame()
    data3['Behavior_list']=d
    data4=pd.DataFrame()
    data4['item_id_list']=e 
    data5 = pd.DataFrame()
    data5['behavior_list'] = f
    # count the number of acts of each group
    data1['Number_of_acts'] = data2['user_id_list'].apply(lambda x: len(x))
    data3['Number_of_acts_UI'] = data4['item_id_list'].apply(lambda x: len(x))
    '''
    print('data1:',end='\n')
    print(data1.head(2),end='\n')
    print('data3:',end='\n')
    print(data3.head(2),end='\n')
    '''
############# Feature of item################
####### Statistics
    #Number of times the product was purchased
    data['2_item_buy'] = data['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    #Number of users who purchased the item
    data1['2_item_buypeople'] = data1['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    #Number of times the product was viewed
    data['2_item_view'] = data['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #Number of users who viewed the item
    data1['2_item_viewpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #Number of times the product was collected
    data['2_item_collect'] = data['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #Number of users who collected the item
    data1['2_item_collectpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #Number of times the product was carted
    data['2_item_add'] = data['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    # Number of users who carted the item
    data1['2_item_addpeople'] = data1['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])

####### Ratio
    #Number of times the product was purchased/Number of times the product was viewed
    data['2_item_buy_view'] = data['2_item_buy']/data['2_item_view']
    #Number of users who purchased the item/Number of users who viewed the item
    data1['2_item_buypeople_viewpeople'] = data1['2_item_buypeople']/data1['2_item_viewpeople']
    #Number of times the product was purchased/Number of times the product was collected
    data['2_item_buy_collect'] = data['2_item_buy'] / data['2_item_collect']
    #Number of users who purchased the item/Number of users who collected the item
    data1['2_item_buypeople_collectpeople'] = data1['2_item_buypeople']/data1['2_item_collectpeople']
    #Number of times the product was purchased/Number of times the product was carted
    data['2_item_buy_add'] = data['2_item_buy'] / data['2_item_add']
    #Number of users who purchased the item/Number of users who carted the item
    data1['2_item_buypeople_addpeople'] = data1['2_item_buypeople']/data1['2_item_addpeople']
    #Number of users who make multiple purchases/Number of users who purchased the product in the two days
    data1['2_item_frequentbuypeople_buypeople'] = data1['2_item_buypeople'] / data1['Number_of_acts']
    #Number of users who viewed the product multiple times/Number of users who purchased the product in the two days
    data1['2_item_frequentviewpeople_viewpeople'] = data1['2_item_viewpeople'] / data1['Number_of_acts']
    #Number of users who collected the product multiple times/Number of users who purchased the product in the two days 
    data1['2_item_frequentcollectpeople_collectpeople'] = data1['2_item_collectpeople'] / data1['Number_of_acts']
    #Number of users who carted the product multiple times/Number of users who purchased the product in the two days
    data1['2_item_frequentaddpeople_addpeople'] = data1['2_item_addpeople'] / data1['Number_of_acts']
    data = data.reset_index()
    data1 = data1.reset_index()
    '''
    print('data:',end='\n')
    print(data.head(2),end='\n')
    print('data1:',end='\n')
    print(data1.head(2),end='\n')
    print('item成功',end='\n')
    '''
############# Feature of GEO(geographic location)################
    data5['4_geo_view'] = data5['behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    data5['4_geo_collect'] = data5['behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    data5['4_geo_add'] = data5['behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    data5['4_geo_buy'] = data5['behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    data5['behavior_total'] = data5['behavior_list'].apply(lambda x: len(x))
    #Number of items purchased in the area / Total number of users in the area
    data5['4_geo_purchasepower'] = data5['4_geo_buy']/data5['behavior_total']
    #Number of items purchased in the area / Number of items viewed in the area
    data5['4_geo_buy_view'] = data5['4_geo_buy']/data5['4_geo_view']
    #Number of items purchased in the area / Number of items collected in the area   
    data5['4_geo_buy_collect'] = data5['4_geo_buy']/data5['4_geo_collect']
    #Number of items purchased in the area to / Number of items carted in the area    
    data5['4_geo_buy_add'] = data5['4_geo_buy']/data5['4_geo_add']
    data5 = data5.reset_index()
    '''
    print('data5:',end='\n')
    print(data5.head(2),end='\n')
    print('GEO成功',end='\n')
    '''
############# Feature of UI################
    ####### Statistics
    #The number of times the user viewed the item
    data3['6_UI_useritemview'] = data3['Behavior_list'].apply(lambda x: 0 if '1' not in x else Counter(x)['1'])
    #The number of times the user collected the item
    data3['6_UI_useritemcollect'] = data3['Behavior_list'].apply(lambda x: 0 if '2' not in x else Counter(x)['2'])
    #The number of times the user carted the item
    data3['6_UI_useritemcart'] = data3['Behavior_list'].apply(lambda x: 0 if '3' not in x else Counter(x)['3'])
    #The number of times the user purchased the item
    data3['6_UI_useritembuy'] = data3['Behavior_list'].apply(lambda x: 0 if '4' not in x else Counter(x)['4'])
    ####### Ratio
    #The number of times the user views the item / The user's total views of all items
    data3['6_UI_useritemview_usertotalview'] = data3['6_UI_useritemview'] / data3['Number_of_acts_UI']
    #The number of times the user collects the item / The user's total collection of all items
    data3['6_UI_useritemcollect_usertotalcollect'] = data3['6_UI_useritemcollect'] / data3['Number_of_acts_UI']
    #The number of times the user carts the item / The user's total amount of all items added to the shopping cart
    data3['6_UI_useritemcart_usertotalcart'] = data3['6_UI_useritemcart'] / data3['Number_of_acts_UI']
    #The number of times the user purchases the item / The user's total purchases of all items
    data3['6_UI_useritembuy_usertotalbuy'] = data3['6_UI_useritembuy'] / data3['Number_of_acts_UI']
    data3 = data3.reset_index()
    '''
    print('data3:',end='\n')
    print(data3.head(2),end='\n')
    print('UI成功',end='\n')
    '''
#############Merge column#############
    df = pd.merge(df, data, how='left', on=['user_id'])
    df = pd.merge(df, data1, how='left', on=['item_id'])
    df = pd.merge(df, data5, how='left', on=['user_geohash1'])
    r_df= pd.merge(df, data3, how='left', on=['user_id', 'item_id'])
    print('success!!',end='\n')
    return r_df

In [35]:
for i in range(1,6):
    locals()['rr_df'+str(i)]=feature(locals()['df'+str(i)]) 
    print(locals()['rr_df'+str(i)].head(2),end='\n')
    locals()['col_df'+str(i)]= [x for x in locals()['rr_df'+str(i)].columns]
    print(locals()['col_df'+str(i)])

success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  275221686              1          NaN          10576

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-15 08  2014-12-15            [1]  [10001082]  [150720867]  ...
1  2014-12-13 14  2014-12-13            [1]  [10001082]  [275221686]  ...

                          Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0                                   [1]                 1                 1
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]                12                12

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 0

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                              1.0                                    0.0
1                              1.0                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                            0.0
1                              0.0                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-08 18  2014-12-08            [1]  [10001082]  [285259775]  ...
1  2014-12-08 07  2014-12-08            [1]  [10001082]  [275221686]  ...

                 Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0                          [1]                 1                 1
1  [1, 1, 1, 1, 1, 1, 1, 1, 1]                 9                 9

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 0

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                              1.0                                    0.0
1                              1.0                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                            0.0
1                              0.0                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-08 18  2014-12-08            [1]  [10001082]  [285259775]  ...
1  2014-12-08 07  2014-12-08            [1]  [10001082]  [275221686]  ...

                 Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0                          [1]                 1                 1
1  [1, 1, 1, 1, 1, 1, 1, 1, 1]                 9                 9

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 0

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                              1.0                                    0.0
1                              1.0                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                            0.0
1                              0.0                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']
success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  285259775              1      97lk14c           4076
1  10001082  275221686              1          NaN          10576

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-08 18  2014-12-08            [1]  [10001082]  [285259775]  ...
1  2014-12-08 07  2014-12-08            [1]  [10001082]  [275221686]  ...

                 Behavior_list Number_of_acts_UI 6_UI_useritemview  \
0                          [1]                 1                 1
1  [1, 1, 1, 1, 1, 1, 1, 1, 1]                 9                 9

   6_UI_useritemcollect  6_UI_useritemcart  6_UI_useritembuy  \
0                     0                  0                 0
1                     0                  0                 0

   6_UI_useritemview_usertotalview  6_UI_useritemcollect_usertotalcollect  \
0                              1.0                                    0.0
1                              1.0                                    0.0

   6_UI_useritemcart_usertotalcart  6_UI_useritembuy_usertotalbuy
0                              0.0                            0.0
1                              0.0                            0.0

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

success!!
    user_id    item_id  behavior_type user_geohash  item_category  \
0  10001082  150720867              1      95qoghe           3200
1  10001082  220586551              1          NaN           7079

            time       time1 behavior_type1    user_id1     item_id1  ...  \
0  2014-12-15 08  2014-12-15            [1]  [10001082]  [150720867]  ...
1  2014-12-14 03  2014-12-14            [1]  [10001082]  [220586551]  ...

  Behavior_list Number_of_acts_UI 6_UI_useritemview  6_UI_useritemcollect  \
0           [1]                 1                 1                     0
1  [1, 4, 1, 1]                 4                 3                     0

   6_UI_useritemcart  6_UI_useritembuy  6_UI_useritemview_usertotalview  \
0                  0                 0                             1.00
1                  0                 1                             0.75

   6_UI_useritemcollect_usertotalcollect  6_UI_useritemcart_usertotalcart  \
0                                    0.0                              0.0
1                                    0.0                              0.0

   6_UI_useritembuy_usertotalbuy
0                           0.00
1                           0.25

[2 rows x 53 columns]
['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category', 'time', 'time1', 'behavior_type1', 'user_id1', 'item_id1', 'user_item_pair', 'user_geohash1', 'Behavior_list_x', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', 'Behavior_list_y', 'Number_of_acts', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', 'behavior_list', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', 'behavior_total', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', 'Behavior_list', 'Number_of_acts_UI', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

In [36]:
####Here you need to manually set the file path
loc = 'D:/Github/PHBS_MLF_2019/Data/Four Days/user_item_pair_'
train5= pd.read_excel(loc + 'test_form.xlsx')
train1234_1= pd.read_excel(loc + 'train_form.xlsx')
train5
train1234_1
'''
train5-18
train1234-8,9,10,17
'''
'''
train1_13,14,15,16,17
train2_7,8,9,10,11
train3_6,7,8,9,10
train4_5,6,7,8,9
test_14,15,16,17,18
'''

'\ntrain1_13,14,15,16,17\ntrain2_7,8,9,10,11\ntrain3_6,7,8,9,10\ntrain4_5,6,7,8,9\ntest_14,15,16,17,18\n'

In [37]:
train1234=train1234_1.reset_index()
train1234['id']=train1234['index']+1
train1234=train1234.drop(['index'],axis=1)
train1234.head(5)

   id   user_id    item_id  label        time
0   1  10001082  150720867      0  2014-12-17
1   2  10001082  275221686      0  2014-12-17
2   3  10001082  220586551      0  2014-12-17
3   4  10001082  209290607      0  2014-12-17
4   5  10001082   22667958      0  2014-12-17

In [38]:
#####The date needs to be set manually here
train1=train1234.loc[(train1234["time"]=="2014-12-17")]
train2=train1234.loc[(train1234["time"]=="2014-12-10")]
train3=train1234.loc[(train1234["time"]=="2014-12-09")]
train4=train1234.loc[(train1234["time"]=="2014-12-08")]
for i in range(1,5):
    print(locals()['train'+str(i)].head(2))

   id   user_id    item_id  label        time
0   1  10001082  150720867      0  2014-12-17
1   2  10001082  275221686      0  2014-12-17
    id   user_id    item_id  label        time
49  50  10001082  285259775      0  2014-12-10
50  51  10001082  275221686      0  2014-12-10
    id   user_id    item_id  label        time
69  70  10001082  285259775      0  2014-12-09
70  71  10001082  275221686      0  2014-12-09
      id   user_id    item_id  label        time
104  105  10001082  275221686      0  2014-12-08
105  106  10001082  275221686      0  2014-12-08

In [44]:
for i in range(1,6):
    locals()['df'+str(i)]=locals()['df'+str(i)].copy(deep=True)

#######match the columns of train/test with df
drop = ['user_id', 'item_id', 'behavior_type', 'user_geohash', 'item_category',
            'time','time1', 'behavior_type1', 'user_id 1', 'user_id1','item_id1', 
            'user_item_pair', 'user_geohash1', 'Behavior_list_x','Behavior_list_y', 
            'Number_of_acts','behavior_total','behavior_list','Behavior_list', 'Number_of_acts_UI']

for i in range(1,6):
    locals()['train_col_'+str(i)]= [x for x in locals()['rr_df'+str(i)].columns if x not in drop]
    locals()['train'+str(i)][locals()['train_col_'+str(i)]] = locals()['rr_df'+str(i)][locals()['train_col_'+str(i)]]

In [45]:
train1_col= [x for x in train1.columns]
print(train1_col)

['id', 'user_id', 'item_id', 'label', 'time', '2_item_buy', '2_item_view', '2_item_collect', '2_item_add', '2_item_buy_view', '2_item_buy_collect', '2_item_buy_add', '2_item_buypeople', '2_item_viewpeople', '2_item_collectpeople', '2_item_addpeople', '2_item_buypeople_viewpeople', '2_item_buypeople_collectpeople', '2_item_buypeople_addpeople', '2_item_frequentbuypeople_buypeople', '2_item_frequentviewpeople_viewpeople', '2_item_frequentcollectpeople_collectpeople', '2_item_frequentaddpeople_addpeople', '4_geo_view', '4_geo_collect', '4_geo_add', '4_geo_buy', '4_geo_purchasepower', '4_geo_buy_view', '4_geo_buy_collect', '4_geo_buy_add', '6_UI_useritemview', '6_UI_useritemcollect', '6_UI_useritemcart', '6_UI_useritembuy', '6_UI_useritemview_usertotalview', '6_UI_useritemcollect_usertotalcollect', '6_UI_useritemcart_usertotalcart', '6_UI_useritembuy_usertotalbuy']

In [46]:
train_1=train1.append([train2,train3,train4])
train_1=train_1.fillna(0)
train_1=train_1.replace(float('inf'),0)
train_2=train_1.sort_index(axis = 0,ascending = True,by = 'id')
train_2.head(10)

train5=train5.fillna(0)
train5=train5.replace(float('inf'),0)
test=train5
test

C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  after removing the cwd from sys.path.

,user_id,item_id,label,time,2_item_buy,2_item_view,2_item_collect,2_item_add,2_item_buy_view,2_item_buy_collect,...,4_geo_buy_collect,4_geo_buy_add,6_UI_useritemview,6_UI_useritemcollect,6_UI_useritemcart,6_UI_useritembuy,6_UI_useritemview_usertotalview,6_UI_useritemcollect_usertotalcollect,6_UI_useritemcart_usertotalcart,6_UI_useritembuy_usertotalbuy
0,10001082,150720867,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,1,0,0,0,1.000000,0.0,0.000000,0.00
1,10001082,220586551,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,3,0,0,1,0.750000,0.0,0.000000,0.25
2,10001082,209290607,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
3,10001082,22667958,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,3,0,0,0,1.000000,0.0,0.000000,0.00
4,10001082,125083630,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
5,10001082,133020432,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,1,0,0,0,1.000000,0.0,0.000000,0.00
6,10001082,275221686,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,6,0,0,0,1.000000,0.0,0.000000,0.00
7,10001082,582649,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,1,0,0,0,1.000000,0.0,0.000000,0.00
8,10001082,377161387,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,2,0,0,0,1.000000,0.0,0.000000,0.00
9,10001082,110790001,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
10,10001082,220586551,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,3,0,0,1,0.750000,0.0,0.000000,0.25
11,10001082,85851739,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,4,0,0,0,1.000000,0.0,0.000000,0.00
12,10001082,278017344,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
13,10001082,85851739,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,4,0,0,0,1.000000,0.0,0.000000,0.00
14,10001082,275221686,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,6,0,0,0,1.000000,0.0,0.000000,0.00
15,10001082,282816229,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
16,10001082,6862367,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
17,10001082,275221686,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,6,0,0,0,1.000000,0.0,0.000000,0.00
18,10001082,275221686,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,6,0,0,0,1.000000,0.0,0.000000,0.00
19,10001082,345696502,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
20,10001082,275221686,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,6,0,0,0,1.000000,0.0,0.000000,0.00
21,10001082,85851739,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,4,0,0,0,1.000000,0.0,0.000000,0.00
22,10001082,22667958,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,3,0,0,0,1.000000,0.0,0.000000,0.00
23,10001082,336390925,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,3,0,0,0,1.000000,0.0,0.000000,0.00
24,10001082,220586551,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,3,0,0,1,0.750000,0.0,0.000000,0.25
25,10001082,220586551,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,3,0,0,1,0.750000,0.0,0.000000,0.25
26,10001082,22667958,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,3,0,0,0,1.000000,0.0,0.000000,0.00
27,10001082,377161387,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,2,0,0,0,1.000000,0.0,0.000000,0.00
28,10001082,188586750,0,2014-12-18,1,33,0,0,0.030303,0.0,...,31.000000,0.428571,1,0,0,0,1.000000,0.0,0.000000,0.00
29,10001082,399970059,0,2014-12-18,1,33,0,0,0.030303,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136119,111694210,365758597,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,3,0,0,0,1.000000,0.0,0.000000,0.00
136120,111694210,358656952,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,8,0,1,0,0.888889,0.0,0.111111,0.00
136121,111694210,313337652,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,2,0,0,0,1.000000,0.0,0.000000,0.00
136122,111694210,62423278,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,2,0,1,0,0.666667,0.0,0.333333,0.00
136123,111694210,57406974,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,2,0,0,0,1.000000,0.0,0.000000,0.00
136124,111694210,306811335,0,2014-12-18,14,452,0,31,0.030973,0.0,...,9.000000,0.360000,5,0,0,0,1.000000,0.0,0.000000,0.00
136125,111694210,170288789,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,3,0,1,0,0.750000,0.0,0.250000,0.00
136126,111694210,387365385,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,1,0,0,0,1.000000,0.0,0.000000,0.00
136127,111694210,136711536,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,2,0,0,0,1.000000,0.0,0.000000,0.00
136128,111694210,225932023,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,7,0,0,0,1.000000,0.0,0.000000,0.00
136129,111694210,84297505,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,7,0,1,2,0.700000,0.0,0.100000,0.20
136130,111694210,61351037,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,4,0,3,0,0.571429,0.0,0.428571,0.00
136131,111694210,196280049,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,4,0,0,0,1.000000,0.0,0.000000,0.00
136132,111694210,262500385,0,2014-12-18,14,452,0,31,0.030973,0.0,...,0.491972,0.369668,6,0,0,0,1.000000,0.0,0.000000,0.00
136133,111699844,161189008,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136134,111699844,7291374,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136135,111699844,218673626,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136136,111699844,292176941,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136137,111699844,216654086,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136138,111699844,28191931,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136139,111699844,49829840,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136140,111699844,22528574,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136141,111699844,258228801,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136142,111699844,114842197,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136143,111699844,27550690,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136144,111699844,114740221,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,2,0,0,0,1.000000,0.0,0.000000,0.00
136145,111699844,285181183,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136146,111699844,114740221,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,2,0,0,0,1.000000,0.0,0.000000,0.00
136147,111699844,222421477,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00
136148,111699844,315280755,0,2014-12-18,0,16,0,0,0.000000,0.0,...,0.000000,0.000000,1,0,0,0,1.000000,0.0,0.000000,0.00

In [47]:
train_2

,id,user_id,item_id,label,time,2_item_buy,2_item_view,2_item_collect,2_item_add,2_item_buy_view,...,4_geo_buy_collect,4_geo_buy_add,6_UI_useritemview,6_UI_useritemcollect,6_UI_useritemcart,6_UI_useritembuy,6_UI_useritemview_usertotalview,6_UI_useritemcollect_usertotalcollect,6_UI_useritemcart_usertotalcart,6_UI_useritembuy_usertotalbuy
0,1,10001082,150720867,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,82.000000,0.367713,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
1,2,10001082,275221686,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,12.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
2,3,10001082,220586551,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,3.0,0.0,0.0,1.0,0.75,0.0,0.0,0.25
3,4,10001082,209290607,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
4,5,10001082,22667958,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,82.000000,0.367713,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
5,6,10001082,125083630,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
6,7,10001082,133020432,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,82.000000,0.367713,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
7,8,10001082,275221686,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,12.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
8,9,10001082,377161387,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,82.000000,0.367713,2.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
9,10,10001082,110790001,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
10,11,10001082,220586551,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,3.0,0.0,0.0,1.0,0.75,0.0,0.0,0.25
11,12,10001082,85851739,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
12,13,10001082,278017344,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
13,14,10001082,216415944,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
14,15,10001082,275221686,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,12.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
15,16,10001082,216415944,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
16,17,10001082,262470188,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
17,18,10001082,216415944,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
18,19,10001082,85851739,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,4.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
19,20,10001082,275221686,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,12.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
20,21,10001082,262470188,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
21,22,10001082,282816229,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
22,23,10001082,362845104,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,2.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
23,24,10001082,275221686,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,12.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
24,25,10001082,6862367,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
25,26,10001082,362845104,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,2.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
26,27,10001082,262470188,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,3.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
27,28,10001082,275221686,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,82.000000,0.367713,12.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
28,29,10001082,345696502,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,1.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
29,30,10001082,275221686,0,2014-12-17,1.0,48.0,0.0,0.0,0.020833,...,0.484549,0.325311,12.0,0.0,0.0,0.0,1.00,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563706,563707,106972148,374789617,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563707,563708,106972148,374789617,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563708,563709,106972148,391929296,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563709,563710,106972148,51483854,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563710,563711,106972148,115376823,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563711,563712,106972148,31136668,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563712,563713,106972148,192864285,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563713,563714,106972148,58422238,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563714,563715,106972148,280431932,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563715,563716,106972148,46879312,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563716,563717,106972148,374789617,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563717,563718,106972148,152539160,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563718,563719,106972148,46879312,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563719,563720,106972148,51483854,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563720,563721,106972148,52236978,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563721,563722,106972148,105424143,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563722,563723,106972148,155353616,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563723,563724,106972148,288104354,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563724,563725,106972148,155353616,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563725,563726,106972148,165978093,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563726,563727,106972148,391929296,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563727,563728,106972148,391929296,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563728,563729,106972148,13414715,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563729,563730,106972148,310788948,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563730,563731,106972148,84151403,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563731,563732,106972148,348723609,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563732,563733,106972148,348723609,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563733,563734,106972148,188111228,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563734,563735,106972148,168096920,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
563735,563736,106972148,192864285,0,2014-12-08,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00

In [ ]:
train_2.to_excel('D:/Github/PHBS_MLF_2019/Data/Four Days/result/user_item_pair_train_XCQ.xlsx')

In [ ]:
test.to_excel('D:/Github/PHBS_MLF_2019/Data/Four Days/result/user_item_pair_test_XCQ.xlsx')